export const STANDARD_SERVICE_TITLES = [
  "Change engine oil",
  "Change engine oil and filter",
  "Rotate tires",
  "Inspect brakes",
  "Replace cabin air filter",
  "Replace engine air filter",
  "Replace brake fluid",
  "Replace spark plugs",
  "Inspect serpentine belt",
  "Change differential fluid (AWD/4WD)",
  "Change transfer case fluid (4WD)",
  "Change power steering fluid",
  "Replace battery",
  "Replace timing belt",
  "Change coolant",
  "Change transmission fluid",
  "Wheel alignment",
  "Inspect suspension",
  "Replace wiper blades",
  "Inspect or replace air filter",
  "Inspect and service final drive",
  "Inspect valve clearance",
] as const;
