import { VehicleKindValue } from "@/lib/vehicle-kind";

const CAR_CATALOG: Record<string, string[]> = {
  Acura: ["Integra", "TLX", "RDX", "MDX", "ZDX"],
  "Alfa Romeo": ["Giulia", "Stelvio", "Tonale", "4C"],
  Audi: ["A3", "A4", "A6", "Q3", "Q5", "Q7", "Q8", "e-tron GT"],
  BMW: ["2 Series", "3 Series", "4 Series", "5 Series", "X1", "X3", "X5", "i4", "iX"],
  Buick: ["Envista", "Encore GX", "Envision", "Enclave"],
  Cadillac: ["CT4", "CT5", "XT4", "XT5", "Escalade", "LYRIQ"],
  Toyota: ["Camry", "Corolla", "RAV4", "Highlander", "Tacoma", "4Runner", "Prius"],
  Honda: ["Civic", "Accord", "CR-V", "Pilot", "HR-V", "Odyssey"],
  Chrysler: ["300", "Pacifica", "Pacifica Plug-in Hybrid", "Voyager"],
  Dodge: ["Durango", "Hornet", "Charger", "Challenger"],
  Ford: ["F-150", "Escape", "Explorer", "Mustang", "Edge", "Bronco"],
  Genesis: ["G70", "G80", "G90", "GV70", "GV80", "GV60"],
  GMC: ["Sierra 1500", "Canyon", "Terrain", "Acadia", "Yukon", "Hummer EV"],
  Chevrolet: ["Silverado 1500", "Equinox", "Traverse", "Tahoe", "Malibu", "Suburban", "Trax", "Blazer"],
  Nissan: ["Altima", "Sentra", "Rogue", "Murano", "Pathfinder", "Frontier"],
  Hyundai: ["Elantra", "Sonata", "Tucson", "Santa Fe", "Palisade", "Kona"],
  Infiniti: ["Q50", "QX50", "QX55", "QX60", "QX80"],
  Jaguar: ["F-PACE", "E-PACE", "I-PACE", "F-TYPE"],
  Kia: ["Forte", "K5", "Sportage", "Sorento", "Telluride", "Soul"],
  "Land Rover": ["Range Rover", "Range Rover Sport", "Defender", "Discovery", "Discovery Sport"],
  Lexus: ["RX", "NX", "ES", "IS", "GX", "UX", "TX", "LS"],
  Lincoln: ["Corsair", "Nautilus", "Aviator", "Navigator"],
  Mazda: ["Mazda3", "CX-30", "CX-5", "CX-50", "CX-70", "CX-90", "MX-5 Miata"],
  "Mercedes-Benz": ["C-Class", "E-Class", "S-Class", "GLA", "GLC", "GLE", "EQS", "EQE"],
  MINI: ["Cooper Hardtop", "Clubman", "Countryman", "Cooper Convertible"],
  Mitsubishi: ["Mirage", "Eclipse Cross", "Outlander", "Outlander PHEV"],
  Porsche: ["718 Cayman", "718 Boxster", "911", "Cayenne", "Macan", "Panamera", "Taycan"],
  Polestar: ["Polestar 2", "Polestar 3", "Polestar 4"],
  Ram: ["1500", "2500", "3500", "ProMaster"],
  Rivian: ["R1T", "R1S", "EDV"],
  Subaru: ["Impreza", "Legacy", "Crosstrek", "Forester", "Outback", "Ascent", "BRZ", "WRX"],
  Tesla: ["Model 3", "Model Y", "Model S", "Model X", "Cybertruck"],
  Volkswagen: ["Jetta", "Passat", "Taos", "Tiguan", "Atlas", "ID.4", "Golf GTI"],
  Volvo: ["S60", "S90", "XC40", "XC60", "XC90", "EX30", "EX90"],
  Jeep: ["Wrangler", "Grand Cherokee", "Cherokee", "Compass", "Gladiator"],
};

// Curated from April 2026 vPIC motorcycle model queries for common U.S. street bikes
// and scooters. We intentionally keep this list focused on supported road-going models.
const MOTORCYCLE_CATALOG: Record<string, string[]> = {
  Honda: [
    "ADV160",
    "Africa Twin",
    "Africa Twin Adventure Sports",
    "CB300R",
    "CB500F",
    "CB500 Hornet",
    "CB650R",
    "CBR300R",
    "CBR500R",
    "CBR600RR",
    "CBR650R",
    "Forza",
    "Fury",
    "Gold Wing",
    "Gold Wing Tour",
    "Grom",
    "Monkey",
    "Navi",
    "NC750X",
    "NT1100",
    "NX500",
    "PCX",
    "Rebel 1100",
    "Rebel 300",
    "Rebel 500",
    "Ruckus",
    "SCL500",
    "Super Cub",
    "Trail125",
    "Transalp",
  ],
  "Harley-Davidson": [
    "Breakout 114",
    "Fat Boy 114",
    "Heritage Classic 114",
    "Low Rider S",
    "Low Rider ST",
    "Nightster",
    "Nightster Special",
    "Pan America",
    "Pan America Special",
    "Road Glide",
    "Road Glide Limited",
    "Road Glide ST",
    "Road King Special",
    "Softail Standard",
    "Sportster S",
    "Street Bob 114",
    "Street Glide",
    "Street Glide Ultra",
    "Tri Glide Ultra",
    "Ultra Limited",
  ],
  Kawasaki: [
    "Eliminator",
    "KLR650",
    "KLX300",
    "KLX300SM",
    "Ninja 400",
    "Ninja 500",
    "Ninja 650",
    "Ninja 1000SX",
    "Ninja ZX-4R",
    "Ninja ZX-6R",
    "Ninja ZX-10R",
    "Versys 650",
    "Versys 1100",
    "Vulcan S",
    "W230",
    "W800",
    "Z400",
    "Z500",
    "Z650",
    "Z650RS",
    "Z900",
    "Z900RS",
  ],
  Yamaha: [
    "Bolt",
    "MT-03",
    "MT-07",
    "MT-09",
    "MT-10",
    "Tenere 700",
    "Tracer 9",
    "V Star 250",
    "VMAX",
    "XMAX",
    "XSR700",
    "XSR900",
    "YZF-R1",
    "YZF-R3",
    "YZF-R7",
    "YZF-R9",
    "Zuma 125",
  ],
  Suzuki: [
    "Boulevard",
    "Burgman 400",
    "DR650SE",
    "GSX-8R",
    "GSX-8S",
    "GSX-S1000",
    "GSX-S1000GT+",
    "GSX-R600",
    "GSX-R750",
    "GSX-R1000R",
    "GSX250R",
    "Hayabusa",
    "Katana",
    "V-Strom 650",
    "V-Strom 1050",
  ],
  Vespa: ["946", "Elettrica", "GTS", "Primavera 150", "Primavera 50", "Sprint 150", "Sprint 50"],
  Piaggio: ["BV400", "Liberty", "MP3", "Piaggio 1"],
};

export const VEHICLE_CATALOGS: Record<VehicleKindValue, Record<string, string[]>> = {
  CAR: CAR_CATALOG,
  MOTORCYCLE: MOTORCYCLE_CATALOG,
};

export const COMMON_MAKES_BY_KIND: Record<VehicleKindValue, string[]> = {
  CAR: Object.keys(CAR_CATALOG),
  MOTORCYCLE: Object.keys(MOTORCYCLE_CATALOG),
};
